### PR TITLE
User's guide in Spanish language

### PR DESCRIPTION
**Pull request by carmenfdezb**
I've started the translations of de user's guide to the Spanish language. I've only translated index.md and language.html with the screenshots, I will translate the other files as soon as possible, but first, I would like to know if I'm doing fine, could you confirm me that?
Thanks again for your excellent work with this project.
Regards.

### CODE REVIEW

**Comment by rinigus** [comment]
It's looking good - exactly as it's supposed to be!  Thank you very much for this work!

Best wishes.

**Comment by rinigus** [comment]
@carmenfdezb , please don't forget to tell me when you are ready. Then I can merge your changes and the documentation will go live. Thank you for this huge work!

**Comment by carmenfdezb** [comment]
Hi @rinigus!
I would like to finish tomorrow, so if you want, I will do a pull request tomorrow with the full translation.
On the other hand, I've noticed there is an error in storage.html: 'Scroll down for continuation' is missing in two instructions windows. I've fixed that in spanish language.
Regards.

**Comment by rinigus** [comment]
@carmenfdezb, great! Then just keep pushing into this branch and when done, let me know. Then I will merge it to the main tree. 

Thank you for finding the missing continuation message - will fix it now.

**Comment by carmenfdezb** [comment]
I've finished the translation!!
I've used your screenshots in PoorMaps, this app is translated to Spanish language but for some reason, the translation doesn't work since I updated Sailfish to 2.1.1 version. I will update those screenshots when this issue is fixed.
Regards.

**Comment by rinigus** [comment]
Thank you very much. I'll merge it and would make accessible in a moment

**Comment by rinigus** [comment]
All merged and linked. I adjusted location of the last caption for profiles. Thank you very much!

**Comment by carmenfdezb** [comment]
Thank you very much, it really looks nice!!

**Pull request merged**
