### PR TITLE
Spanish language

### PR DESCRIPTION
**Pull request by carmenfdezb**
Added translation to Spanish language

### CODE REVIEW

**Comment by rinigus** [comment]
Thank you very much! I have not marked that for Sailfish only harbour- version is needed. The other .ts file is for regular Linux and I am not sure how to deploy it correctly at this time.

Thank you for your great work! I'll merge it probably tomorrow. Would you mind if I acknowledge you in About for your work on translation?

Kind regards,

rinigus

PS: We'll have to think how to add routing commands to translation. It should be future proof and allow us to use it for spoken instructions as well. Probably, solution is simple, but let me sleep on it.

**Comment by carmenfdezb** [comment]
It's a pleasure for me, thanks to you for developing this excellent app ;)

**Comment by rinigus** [comment]
Just to let you know: I have an idea on how to implement routing instructions in a way that would allow to translate them to other languages as well using standard tools. It would take a bit of time to implement it and I will let you know via this issue comment when its ready.

**Comment by carmenfdezb** [comment]
👍

**Comment by rinigus** [comment]
Hi! I think its ready for a new round. I added a README for translations (under translations folder). The new strings should allow you to get translated routing instructions as well (the ones you will see in Poor Maps, for example). 

Thank you again!

**Comment by carmenfdezb** [comment]
Done! ;)

**Pull request merged**
