### PR TITLE
Update harbour-osmscout-server-sk.ts

### PR DESCRIPTION
**Pull request by okruhliak**
First translation to Slovak

### CODE REVIEW

**Comment by rinigus** [comment]
Why did you not use transifex.com?

**Comment by okruhliak** [comment]
I use it, but I didn't find the link in the application or in OpenRepos, so I went straight to Github, sorry. Should I convert it to Transifex?

**Comment by rinigus** [comment]
Link is in https://github.com/rinigus/osmscout-server/blob/master/translations/README.md for translators.

I'll merge it and try to push translations over to transifex. Hopefully, it will work.

**Comment by rinigus** [comment]
Looks like it worked and is now part of transifex project as well. Thanks!

**Comment by okruhliak** [comment]
Thanks well! :)

**Pull request merged**
