### PR TITLE
Fix drawer on UT again

### PR DESCRIPTION
**Pull request by jonnius**
This PR:
* reverts https://github.com/rinigus/osmscout-server/commit/6dc09e39f1793fd7149380f1d0883b040539fc56 to fix the drawer on UT again
* configures clickable to ignore the click review, because the app is unconfined and Clickable now let's the build fail if the review fails

see #396

### CODE REVIEW

**Comment by jonnius** [comment]
We need to hold this back until whatever change is on the UT devel change has reached stable. Because currently this change breaks the drawer on UT stable.

**Comment by Flohack74** [comment]
Can you try to upgrade instead to QtQuick 2.12 everywhere? We did this https://gitlab.com/ubports/development/core/qqc2-suru-style/-/merge_requests/58 and maybe thats the cause?

**Comment by rinigus** [comment]
@Flohack74: I cannot do that for the platform independent bits of the code - it still has to run on SFOS with 5.6 Qt. But we can update in UT specific code.

**Comment by Flohack74** [comment]
@rinigus I see so maybe its really an edge case but I wonder if other native UT apps could be affected by this. Is there any error in the logfiles when that happens?

**Comment by Danfro** [comment]
Just checked the log on my UT device and saw some errors
```
qml: Error while creating component
qml: qrc:/qml/MainMenu.qml:27 Type MenuDrawerPL unavailable
qrc:/qml/platform/MenuDrawerPL.qml:34 Cannot override FINAL property
qrc:/qml/platform/ApplicationWindowPL.qml:60: TypeError: Value is null and could not be converted to an object
qrc:/qml/platform/ApplicationWindowPL.qml:82: TypeError: Cannot call method 'open' of null
```
Those errors are regarding those files: 
- [MenuDrawerPL.qml](https://github.com/rinigus/osmscout-server/blob/master/gui/qml/platform.qtcontrols/MenuDrawerPL.qml)
- called there ^^ is [MenuDrawerItemPL.qml](https://github.com/rinigus/osmscout-server/blob/master/gui/qml/platform.qtcontrols/MenuDrawerItemPL.qml)
- [MainMenu.qml](https://github.com/rinigus/osmscout-server/blob/master/gui/qml/MainMenu.qml)

Others might be relevant too. But one thing those listed above do have in common, they do `import QtQuick 2.0` wich is Qt 5.0, right? Maybe raising this to `import QtQuick 2.6` = Qt 5.6 might be enough to solve the problem?

Just a guess without sticking my head too deep into the code.

**Comment by jonnius** [comment]
Just for reference, I tried setting the import versions of QtQuick and QtQuick.Controls on all QML files to 2.12. It doesn't solve the issue.

**Comment by Danfro** [comment]
Good (or not), but at least that is ruled out. Thanks @jonnius .

**Pull request merged**
