### PR TITLE
Update harbour-osmscout-server-sv.ts

### PR DESCRIPTION
**Pull request by eson57**

### CODE REVIEW

**Comment by eson57** [comment]
Here's the update to. :)

**Comment by rinigus** [comment]
And 0.5.3 got juuuusssttt published.... :) Is it OK if I'll merge it, but the new release would wait a bit (maybe a week) to consolidate the translations?

**Comment by eson57** [comment]
Of course it is. I wouldn't  expect anything else.  :)

**Comment by rinigus** [comment]
Thank you - changes merged

**Comment by rinigus** [comment]
Hi, 

I am preparing a new release with a major update in search engine. As a result, I am still busy with its preparations (postal branch) and would prefer not to release 0.5.4, but move immediately to the next version 0.6.0. I hope its OK and you could wait with publishing your updated translation.

Best wishes,

rinigus

**Comment by eson57** [comment]
Of cource it's ok.. :)

**Pull request merged**
