### PR TITLE
Master

### PR DESCRIPTION
**Pull request by carmenfdezb**
Translation updated

### CODE REVIEW

**Comment by rinigus** [comment]
Thank you very very much! Merging

**Comment by rinigus** [comment]
And your changes are published as 0.4.1 release available at OpenRepos :)

**Comment by carmenfdezb** [comment]
Great!! Thank you so much!!
I need to fix some translations, but it's not important, it can wait for the next update.
On the other hand, status is always 'idle', is it right?

**Comment by rinigus** [comment]
Yes, Idle is OK. That means it is not rendering or searching/routing right
now. If you start moving around in Poor Maps and if you don't have the map
tiles in your Poor Maps cache, the status will change and tell you how many
jobs does it have waiting.

**Comment by carmenfdezb** [comment]
Ok, thanks!

**Pull request merged**
